apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  SECRET_KEY: "P7nhgonTcoI2FDuX1ldYPRuFPYrPpB_8r9ZIm9ZVKVo"
  DB_PASSWORD: "password123"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_USER: "admin"
  DB_NAME: "microservices"
  DATABASE_URL: "postgresql+asyncpg://admin:password123@postgres-service:5432/microservices"
  AUTH_SERVICE_URL: "http://auth-service:8001"
  NOTES_SERVICE_URL: "http://notes-service:8002"